version: "3"

volumes:
  node_modules:

services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    env_file:
      - ./.env